trigger:
  - main   # or 'master' if your branch is master

pool:
  vmImage: 'windows-latest'   # PowerShell tasks need Windows agents

steps:
  # Install dependencies
  - task: PowerShell@2
    displayName: "Install dependencies"
    inputs:
      targetType: 'inline'
      script: 'npm ci'
      workingDirectory: 'tests/'

  # Run Playwright tests on Azure Playwright Testing Service
  - task: AzureCLI@2
    displayName: "Run Playwright Tests on Azure Cloud"
    inputs:
      azureSubscription: RalliantSC   # replace with your service connection name
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        npx playwright test -c playwright.service.config.ts --workers=20
    env:
      PLAYWRIGHT_SERVICE_URL: $(PLAYWRIGHT_SERVICE_URL)
      # PLAYWRIGHT_SERVICE_ACCESS_TOKEN: $(PLAYWRIGHT_SERVICE_ACCESS_TOKEN) # Use Entra ID instead
    addSpnToEnvironment: true
    workingDirectory: './tests'

  # Publish Playwright HTML report as pipeline artifact  
  - task: PublishPipelineArtifact@1
    displayName: "Upload Playwright report"
    inputs:
      targetPath: 'playwright-report'   # folder where Playwright saves HTML report
      artifact: 'PlaywrightReport'
      publishLocation: 'pipeline'
